#!/usr/bin/env python3
"""Write docs/TOOLS.md from the tool registry and the tool docstrings, or check that the file is up to date.

Usage:

uv run python scripts/generate_docs.py           # rewrite docs/TOOLS.md
uv run python scripts/generate_docs.py --check   # exit 1 when docs/TOOLS.md differs from the registry
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from pathlib import Path

from evolution_api_mcp import context, policy, registry, tools
from evolution_api_mcp.server import build_server
from evolution_api_mcp.toolsets import DEFAULT_TOOLSETS, TOOLSET_ORDER, TOOLSETS

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "TOOLS.md"

SHORT_INTEGRATION = {
    registry.BAILEYS: "Baileys",
    registry.BUSINESS: "Business",
    registry.EVOLUTION: "Evolution",
}


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _integrations(spec: registry.ToolSpec) -> str:
    if spec.integrations == registry.ALL:
        return "all"
    return ", ".join(SHORT_INTEGRATION[name] for name in sorted(spec.integrations))


def _first_lines() -> dict[str, str]:
    """The first docstring line of every tool, as the server publishes it (the tool description)."""
    listed = asyncio.run(build_server(mode="local").list_tools())
    return {tool.name: (tool.description or "").strip().splitlines()[0] for tool in listed}


def _hosted_business_surface() -> list[str]:
    """Names a hosted WHATSAPP-BUSINESS connection with the standard policy and every toolset can call."""
    connection = context.Connection(
        mode="hosted",
        policy="standard",
        toolsets=frozenset(TOOLSET_ORDER),
        allow=None,
        deny=policy.DEFAULT_DENY,
        deny_is_default=True,
        irreversible_granted=False,
        identity=context.InstanceIdentity(name="instance", integration=registry.BUSINESS),
        subject="t_docs",
        default_delay_ms=1200,
        max_writes_per_minute=30,
        max_reads_per_minute=120,
    )
    return [spec.name for spec in registry.specs() if policy.visible(spec, connection)]


def render() -> str:
    tools.load_all()
    specs = registry.specs()
    first_lines = _first_lines()
    surface = _hosted_business_surface()

    lines = [
        "# Tools",
        "",
        "<!-- Generated by scripts/generate_docs.py from the tool registry. Do not edit by hand. -->",
        "",
        f"{len(specs)} tools in {len(TOOLSET_ORDER)} toolsets. The local server registers all of them; the hosted",
        f"server registers {sum(1 for spec in specs if not spec.local_only)} (the local-only tools are left out).",
        "Which of them a connection sees also depends on its enabled toolsets, its policy and the integration of its",
        "instance; see the README.",
        "",
        "Columns: **Kind** is `read`, `write`, `destructive` (sends to other people, or replaces or removes",
        "something) or `irreversible` (cannot be undone from this server). **Integrations** are the Evolution",
        "integrations the tool works on: Baileys is `WHATSAPP-BAILEYS`, Business is `WHATSAPP-BUSINESS`, Evolution",
        "is `EVOLUTION`.",
        "**Local only** tools are not offered by the hosted server.",
        "",
    ]
    for toolset in TOOLSET_ORDER:
        members = [spec for spec in specs if spec.toolset == toolset]
        suffix = " (default)" if toolset in DEFAULT_TOOLSETS else ""
        lines += [
            f"## {toolset}{suffix}",
            "",
            f"{TOOLSETS[toolset]} {len(members)} tools.",
            "",
            "| Tool | Title | Kind | Integrations | Local only | What it does |",
            "|---|---|---|---|---|---|",
        ]
        for spec in members:
            lines.append(
                f"| `{spec.name}` | {_cell(spec.title)} | {spec.kind} | {_integrations(spec)} | "
                f"{'yes' if spec.local_only else 'no'} | {_cell(first_lines[spec.name])} |"
            )
        lines.append("")

    lines += [
        "## Hosted surface for WhatsApp Business Platform instances",
        "",
        f"A hosted connection to a `WHATSAPP-BUSINESS` instance with the standard policy and every toolset enabled can"
        f" call {len(surface)} tools. This is the surface the directory listings describe.",
        "",
    ]
    lines += [f"- `{name}`" for name in surface]
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/TOOLS.md from the tool registry.")
    parser.add_argument("--check", action="store_true", help="exit 1 when docs/TOOLS.md is out of date")
    args = parser.parse_args(argv)

    expected = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != expected:
            print(f"{OUTPUT} is out of date: run `uv run python scripts/generate_docs.py`.", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
